name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export BUN_INSTALL=\"$HOME/.bun\"" >> $GITHUB_ENV
          echo "export PATH=\"$HOME/.bun/bin:$PATH\"" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Install Dependencies
        run: bun install

      - name: Install Firebase CLI
        run: bun add -g firebase-tools

      - name: Login to Firebase
        run: firebase login:ci --no-localhost --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Prebuild Angular with Firebase Variables
        run: bun run prebuild

      - name: Build Angular App
        run: bun run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIMEDAR_C7287 }}
          channelId: live
          projectId: climedar-c7287
